DROP TABLE RESULTADO;

CREATE TABLE RESULTADO (
	NR_SEQUENCIA	NUMBER(10)		PRIMARY KEY,
	VL_I			    NUMBER(10,2)	    NOT NULL,
	VL_Y			    NUMBER(10,2)	    NOT NULL,
	DS_OPERACAO		VARCHAR(15)		NOT NULL,
	VL_RESULT		  NUMBER(10,2)	  NOT NULL
);

CREATE SEQUENCE RESULTADO_SEQ
START WITH     1
INCREMENT BY   1
NOMAXVALUE 
NOMINVALUE
NOCACHE
NOCYCLE;

INSERT INTO RESULTADO (NR_SEQUENCIA, VL_I, VL_Y, DS_OPERACAO, VL_RESULT) VALUES (RESULTADO_SEQ.NEXTVAL, 2.5, 5.5, 'soma', 8.0);

DELETE FROM RESULTADO;

COMMIT;

SELECT COUNT(*) FROM RESULTADO;