
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContaCliente", targetNamespace = "http://webServiceServidor/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContaCliente {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCliente", targetNamespace = "http://webServiceServidor/", className = "webservice.GetCliente")
    @ResponseWrapper(localName = "getClienteResponse", targetNamespace = "http://webServiceServidor/", className = "webservice.GetClienteResponse")
    @Action(input = "http://webServiceServidor/ContaCliente/getClienteRequest", output = "http://webServiceServidor/ContaCliente/getClienteResponse")
    public String getCliente();

}
