
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContaClienteService", targetNamespace = "http://webServiceServidor/", wsdlLocation = "http://localhost:5097/cliente?wsdl")
public class ContaClienteService
    extends Service
{

    private final static URL CONTACLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACLIENTESERVICE_EXCEPTION;
    private final static QName CONTACLIENTESERVICE_QNAME = new QName("http://webServiceServidor/", "ContaClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5097/cliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACLIENTESERVICE_WSDL_LOCATION = url;
        CONTACLIENTESERVICE_EXCEPTION = e;
    }

    public ContaClienteService() {
        super(__getWsdlLocation(), CONTACLIENTESERVICE_QNAME);
    }

    public ContaClienteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACLIENTESERVICE_QNAME, features);
    }

    public ContaClienteService(URL wsdlLocation) {
        super(wsdlLocation, CONTACLIENTESERVICE_QNAME);
    }

    public ContaClienteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACLIENTESERVICE_QNAME, features);
    }

    public ContaClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContaClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContaCliente
     */
    @WebEndpoint(name = "ContaClientePort")
    public ContaCliente getContaClientePort() {
        return super.getPort(new QName("http://webServiceServidor/", "ContaClientePort"), ContaCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContaCliente
     */
    @WebEndpoint(name = "ContaClientePort")
    public ContaCliente getContaClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServiceServidor/", "ContaClientePort"), ContaCliente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACLIENTESERVICE_EXCEPTION!= null) {
            throw CONTACLIENTESERVICE_EXCEPTION;
        }
        return CONTACLIENTESERVICE_WSDL_LOCATION;
    }

}
