CREATE TABLE RENDA_PESSOA_FISICA (
ID NUMERIC(10) PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
IDADE NUMERIC(3) NOT NULL,
RENDA NUMERIC(10,2) NOT NULL,
FONTE VARCHAR(250) NOT NULL,
DATA_RENDA DATE NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);