CREATE TABLE BEM_PESSOA_FISICA (
ID NUMERIC(10) PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(250) NOT NULL,
VALOR NUMERIC(10,2) NOT NULL,
ENDERECO VARCHAR(250) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);