CREATE TABLE USUARIO (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(150) NOT NULL UNIQUE,
SENHA VARCHAR(60) NOT NULL,
SITUACAO INT NOT NULL,
PERFIL INT NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);