CREATE TABLE FUNCIONARIO (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL UNIQUE,
RG VARCHAR(9) NOT NULL UNIQUE,
VALOR_HORA DECIMAL(7,2) NOT NULL,
QT_HORAS_TRABALHO_DIA DECIMAL(4,2) NOT NULL,
QT_HORAS_ALMOCO DECIMAL(3,2) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL,
EMPRESA BIGINT NOT NULL,
USUARIO BIGINT NOT NULL UNIQUE,
CONSTRAINT FUNCIONARIO_EMPRESA_FK FOREIGN KEY(EMPRESA) REFERENCES EMPRESA(ID),
CONSTRAINT FUNCIONARIO_USUARIO_FK FOREIGN KEY(USUARIO) REFERENCES USUARIO(ID)
);