CREATE TABLE LANCAMENTO (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
DATA TIMESTAMP NOT NULL,
DESCRICAO VARCHAR(255),
LOCALIZACAO VARCHAR(150),
TIPO INT NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL,
FUNCIONARIO BIGINT NOT NULL,
CONSTRAINT LANCAMENTO_FUNCIONARIO_FK FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
);