CREATE TABLE DIVIDA (
ID NUMERIC(10) PRIMARY KEY,
DESCRICAO VARCHAR(250) NOT NULL,
VALOR NUMERIC(10,2) NOT NULL,
DATA_VENCIMENTO DATE NOT NULL,
QUITADO NUMERIC(1) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL,
PESSOA_FISICA NUMERIC(10) NOT NULL,
CONSTRAINT PESSOA_FISICA_DIVIDA_FK FOREIGN KEY(PESSOA_FISICA) REFERENCES PESSOA_FISICA(ID)
);