CREATE TABLE USUARIO (
ID NUMERIC(10) PRIMARY KEY,
EMAIL VARCHAR(150) NOT NULL UNIQUE,
SENHA VARCHAR(60) NOT NULL,
SITUACAO NUMERIC(2) NOT NULL,
PERFIL NUMERIC(2) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);