CREATE TABLE FUNCIONARIO (
ID NUMERIC(10) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL UNIQUE,
RG VARCHAR(9) NOT NULL UNIQUE,
VALOR_HORA NUMERIC(10,2) NOT NULL,
QT_HORAS_TRABALHO_DIA NUMERIC(5,2) NOT NULL,
QT_HORAS_ALMOCO NUMERIC(5,2) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL,
EMPRESA NUMERIC(10) NOT NULL,
USUARIO NUMERIC(10) NOT NULL UNIQUE,
CONSTRAINT FUNCIONARIO_EMPRESA_FK FOREIGN KEY(EMPRESA) REFERENCES EMPRESA(ID),
CONSTRAINT FUNCIONARIO_USUARIO_FK FOREIGN KEY(USUARIO) REFERENCES USUARIO(ID)
);