CREATE TABLE LANCAMENTO (
ID NUMERIC(10) PRIMARY KEY,
DATA TIMESTAMP NOT NULL,
DESCRICAO VARCHAR(255),
LOCALIZACAO VARCHAR(150),
TIPO NUMERIC(2) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL,
FUNCIONARIO NUMERIC(10) NOT NULL,
CONSTRAINT LANCAMENTO_FUNCIONARIO_FK FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
);