CREATE TABLE AUDITORIA (
ID NUMERIC(10) PRIMARY KEY,
DATA TIMESTAMP NOT NULL,
API VARCHAR(100) NOT NULL,
INPUT_JSON TEXT,
OUTPUT_JSON TEXT,
STATUS NUMERIC(2) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);