package apresentacao;

import Negocio.Categoria;
import Negocio.Comercial;
import Negocio.Comodo;
import Negocio.Edificacao;
import Negocio.Residencial;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class Apresentacao extends javax.swing.JFrame {

    private HashMap<String, Categoria> listaCategoria = new HashMap();
    private Map<String, Edificacao> edificacoes;

    Apresentacao edificacao;

    private void cargaInicial() {
        Categoria novaCategoria = new Categoria("Quarto", 15);
        listaCategoria.put("Quarto", novaCategoria);
        categoriaComodoComboBox.addItem("Quarto");

        novaCategoria = new Categoria("Sala TV", 15);
        listaCategoria.put("Sala TV", novaCategoria);
        categoriaComodoComboBox.addItem("Sala TV");

        novaCategoria = new Categoria("Sala", 18);
        listaCategoria.put("Sala", novaCategoria);
        categoriaComodoComboBox.addItem("Sala");

        novaCategoria = new Categoria("Cozinha", 18);
        listaCategoria.put("Cozinha", novaCategoria);
        categoriaComodoComboBox.addItem("Cozinha");

        novaCategoria = new Categoria("Varanda", 13);
        listaCategoria.put("Varanda", novaCategoria);
        categoriaComodoComboBox.addItem("Varanda");

        novaCategoria = new Categoria("Recepção", 15);
        listaCategoria.put("Recepção", novaCategoria);
        categoriaComodoComboBox.addItem("Recepção");

        novaCategoria = new Categoria("Escritório", 20);
        listaCategoria.put("Escritório", novaCategoria);
        categoriaComodoComboBox.addItem("Escritório");

        novaCategoria = new Categoria("Banheiro", 20);
        listaCategoria.put("Banheiro", novaCategoria);
        categoriaComodoComboBox.addItem("Banheiro");

        novaCategoria = new Categoria("Corredor", 12);
        listaCategoria.put("Corredor", novaCategoria);
        categoriaComodoComboBox.addItem("Corredor");
    }

    protected enum Abas {

        residencial(0), comercial(1);

        private int valor;

        private Abas(int valor) {
            this.valor = valor;
        }
    }

    /**
     * Creates new form Apresentacao
     */
    public Apresentacao() {
        initComponents();
        this.setLocationRelativeTo(null);
        listaCategoria = new HashMap<String, Categoria>();
        edificacoes = new HashMap<String, Edificacao>();
        cargaInicial();
    }

    public class MinhaException extends Exception {

        private String msg;

        public MinhaException(String msg) {
            super(msg);
            this.msg = msg;
        }

        @Override
        public String getMessage() {
            return msg;
        }
    }

    public class ArgumentoInvalidoException extends MinhaException {

        public ArgumentoInvalidoException() {
            super("Argumento invalido");
        }
    }

    public class ArgumentoNuloException extends MinhaException {

        public ArgumentoNuloException(String campo) {
            super("Argumento nulo: " + campo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtPotencia = new javax.swing.JTextField();
        incluirCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        edificacoesCalcularComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        btCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TabbedPannel = new javax.swing.JTabbedPane();
        tRes = new javax.swing.JPanel();
        lbQtdMoradores = new javax.swing.JLabel();
        lbResponsavel = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        ResRes = new javax.swing.JTextField();
        TipoRes = new javax.swing.JTextField();
        lbExemplo = new javax.swing.JLabel();
        EndRes = new javax.swing.JTextField();
        NumRes = new javax.swing.JTextField();
        QtdRes = new javax.swing.JTextField();
        tCom = new javax.swing.JPanel();
        TipoCom = new javax.swing.JTextField();
        EndCom = new javax.swing.JTextField();
        NumCom = new javax.swing.JTextField();
        lbRamo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbResponsavel1 = new javax.swing.JLabel();
        ResCom = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        edificacoesComodoComboBox = new javax.swing.JComboBox();
        categoriaComodoComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLargura = new javax.swing.JTextField();
        txtComprimento = new javax.swing.JTextField();
        btIncluirComodo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcula Consumo");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Categoria:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Potência/m²:");

        incluirCategoria.setText("Incluir Categoria");
        incluirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirCategoriaActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btCalcular.setText("Calcular");
        btCalcular.setToolTipText("");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtCategoria))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edificacoesCalcularComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCalcular)
                        .addGap(58, 58, 58))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(incluirCategoria)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incluirCategoria)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edificacoesCalcularComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalcular))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categoria", jPanel1);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbQtdMoradores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbQtdMoradores.setText("Qtd. Moradores:");

        lbResponsavel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbResponsavel.setText("Responsável:");

        lbTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTipo.setText("Tipo:");

        lbEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEndereco.setText("Endereço:");

        lbNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNumero.setText("Número:");

        lbExemplo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbExemplo.setText("(Casa, Apartamento, ...)");

        javax.swing.GroupLayout tResLayout = new javax.swing.GroupLayout(tRes);
        tRes.setLayout(tResLayout);
        tResLayout.setHorizontalGroup(
            tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tResLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbResponsavel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbQtdMoradores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tResLayout.createSequentialGroup()
                        .addComponent(TipoRes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbExemplo))
                    .addComponent(QtdRes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumRes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResRes)
                    .addComponent(EndRes, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        tResLayout.setVerticalGroup(
            tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tResLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsavel)
                    .addComponent(ResRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(TipoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExemplo))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(EndRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumero)
                    .addComponent(NumRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtdRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQtdMoradores))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        TabbedPannel.addTab("Residencial", tRes);

        lbRamo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRamo.setText("Ramo de Atividade:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Endereço:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Número:");

        lbResponsavel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbResponsavel1.setText("Empresa:");

        javax.swing.GroupLayout tComLayout = new javax.swing.GroupLayout(tCom);
        tCom.setLayout(tComLayout);
        tComLayout.setHorizontalGroup(
            tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tComLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tComLayout.createSequentialGroup()
                        .addComponent(lbResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResCom))
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbRamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumCom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndCom, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        tComLayout.setVerticalGroup(
            tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tComLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsavel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(ResCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRamo, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(TipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(EndCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(117, 117, 117))
        );

        TabbedPannel.addTab("Comercial", tCom);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPannel)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edificação", jPanel2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Categoria:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Edificações");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Largura:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Comprimento:");

        btIncluirComodo.setText("Incluir Comodo");
        btIncluirComodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirComodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edificacoesComodoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaComodoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btIncluirComodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edificacoesComodoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaComodoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btIncluirComodo)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comodo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incluirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirCategoriaActionPerformed
        if (txtCategoria.getText() == null || txtCategoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome da Categoria deve ser Informado!");
        } else {
            if (txtPotencia.getText() == null || txtPotencia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Potencia deve ser Informada!");
            } else {

                try {

                    int potencia;

                    try {
                        potencia = Integer.parseInt(txtPotencia.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Valor Potência Incorreto: " + e.getMessage());
                        return;
                    }

                    Categoria novaCategoria = new Categoria(txtCategoria.getText(),
                            potencia);

                    listaCategoria.put(txtCategoria.getText(), novaCategoria);

                    JOptionPane.showMessageDialog(this, "Categoria Cadastrada!");
                    categoriaComodoComboBox.addItem(txtCategoria.getText());
                    txtCategoria.setText(" ");
                    txtPotencia.setText(" ");
                    txtCategoria.grabFocus();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Categoria!");
                }
            }
        }
    }//GEN-LAST:event_incluirCategoriaActionPerformed

    public Map<String, Edificacao> getEdificacoes() {
        return this.edificacoes;
    }

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        txtResultado.setText("");
        try {
            Edificacao t = edificacoes.get(edificacoesCalcularComboBox.getSelectedItem().toString());
            txtResultado.append(t.toString());
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Erro ao Processar a Solicitação!");
        }


    }//GEN-LAST:event_btCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Edificacao e = null;
            if (TabbedPannel.getSelectedIndex() == Abas.residencial.valor) {

                if (ResRes.getText() == null || ResRes.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Responsavel");
                }

                if (NumRes.getText() == null || NumRes.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Numero");
                }

                if (EndRes.getText() == null || EndRes.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Endereço");
                }

                if (QtdRes.getText() == null || QtdRes.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Qtd. Moradores");
                }

                if (TipoRes.getText() == null || TipoRes.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Tipo");
                }

                e = new Residencial(ResRes.getText(),
                        EndRes.getText(),
                        Integer.parseInt(NumRes.getText()),
                        Integer.parseInt(QtdRes.getText()),
                        TipoRes.getText());
                edificacoes.put(ResRes.getText(), e);
                edificacoesComodoComboBox.addItem(ResRes.getText());
                edificacoesCalcularComboBox.addItem(ResRes.getText());
            } else {

                if (ResCom.getText() == null || ResCom.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Empresa");
                }

                if (EndCom.getText() == null || EndCom.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Endereço");
                }

                if (NumCom.getText() == null || NumCom.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Numero");
                }

                if (TipoCom.getText() == null || TipoCom.getText().isEmpty()) {
                    throw new ArgumentoNuloException("Ramo de Atividade");
                }

                e = new Comercial(ResCom.getText(),
                        EndCom.getText(),
                        Integer.parseInt(NumCom.getText()),
                        TipoCom.getText());
                edificacoes.put(ResCom.getText(), e);
                edificacoesComodoComboBox.addItem(ResCom.getText());
                edificacoesCalcularComboBox.addItem(ResCom.getText());
            }

            JOptionPane.showMessageDialog(this, "Categoria Cadastrada!");
            LimparCamposEdificacao();

        } catch (MinhaException me) {
            System.err.println(me.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btIncluirComodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirComodoActionPerformed
        try {

            Edificacao t = edificacoes.get(edificacoesComodoComboBox.getSelectedItem().toString());

            Categoria c = listaCategoria.get(categoriaComodoComboBox.getSelectedItem().toString());

            double largura = 0;
            double comprimento = 0;
            try {
                largura = Double.parseDouble(txtLargura.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor Largura Invalido: " + e.getMessage());
                return;
            }

            try {
                comprimento = Double.parseDouble(txtComprimento.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor Comprimento Invalido: " + e.getMessage());
                return;
            }

            t.addComodo(new Comodo(largura, comprimento, c));

            JOptionPane.showMessageDialog(this, "Comodo Adicionado!");
            LimparCamposComodo();
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Erro ao Incluir Comodo!");
        }

    }//GEN-LAST:event_btIncluirComodoActionPerformed

    private void LimparCamposEdificacao() {
        ResCom.setText("");
        EndCom.setText("");
        NumCom.setText("");
        TipoCom.setText("");
        ResRes.setText("");
        EndRes.setText("");
        NumRes.setText("");
        QtdRes.setText("");
        TipoRes.setText("");
    }

    private void LimparCamposComodo() {
        txtLargura.setText("");
        txtComprimento.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Apresentacao().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EndCom;
    private javax.swing.JTextField EndRes;
    private javax.swing.JTextField NumCom;
    private javax.swing.JTextField NumRes;
    private javax.swing.JTextField QtdRes;
    private javax.swing.JTextField ResCom;
    private javax.swing.JTextField ResRes;
    private javax.swing.JTabbedPane TabbedPannel;
    private javax.swing.JTextField TipoCom;
    private javax.swing.JTextField TipoRes;
    private javax.swing.JButton btCalcular;
    private javax.swing.JToggleButton btIncluirComodo;
    private javax.swing.JComboBox categoriaComodoComboBox;
    private javax.swing.JComboBox edificacoesCalcularComboBox;
    private javax.swing.JComboBox edificacoesComodoComboBox;
    private javax.swing.JButton incluirCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbExemplo;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbQtdMoradores;
    private javax.swing.JLabel lbRamo;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbResponsavel1;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JPanel tCom;
    private javax.swing.JPanel tRes;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtComprimento;
    private javax.swing.JTextField txtLargura;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables

}
