package apresentacao;

import Negocio.Categoria;
import java.util.HashMap;
import javax.swing.JOptionPane;

public class CadCategoria extends javax.swing.JDialog {

    private HashMap<String, Categoria> listaCategoria = new HashMap();

    /**
     * Creates new form CadCategoria
     */
    public CadCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaCategoria = new HashMap<String, Categoria>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntCargaInicial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtCategoria = new javax.swing.JTextField();
        txtPotencia = new javax.swing.JTextField();
        lbCategoria = new javax.swing.JLabel();
        lbPotencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bntCargaInicial.setText("Carga Inicial");
        bntCargaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCargaInicialActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro de Categorias");

        jToggleButton1.setText("Incluir");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCategoria.setLabelFor(txtCategoria);
        lbCategoria.setText("Categoria:");

        lbPotencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPotencia.setText("Potência/m²:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bntCargaInicial)
                        .addGap(47, 47, 47)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(lbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPotencia))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCargaInicial)
                    .addComponent(jToggleButton1))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public HashMap<String, Categoria> getCategorias() {
        return this.listaCategoria;
    }

    private void bntCargaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCargaInicialActionPerformed
        Categoria novaCategoria = new Categoria("Quarto", 15);
        listaCategoria.put("Quarto", novaCategoria);

        novaCategoria = new Categoria("Sala TV", 15);
        listaCategoria.put("Sala TV", novaCategoria);

        novaCategoria = new Categoria("Sala", 18);
        listaCategoria.put("Sala", novaCategoria);

        novaCategoria = new Categoria("Cozinha", 18);
        listaCategoria.put("Cozinha", novaCategoria);

        novaCategoria = new Categoria("Varanda", 13);
        listaCategoria.put("Varanda", novaCategoria);

        novaCategoria = new Categoria("Recepção", 15);
        listaCategoria.put("Recepção", novaCategoria);

        novaCategoria = new Categoria("Escritório", 20);
        listaCategoria.put("Escritório", novaCategoria);

        novaCategoria = new Categoria("Banheiro", 20);
        listaCategoria.put("Banheiro", novaCategoria);

        novaCategoria = new Categoria("Corredor", 12);
        listaCategoria.put("Corredor", novaCategoria);

        JOptionPane.showMessageDialog(this, "Carga Inicial Efetuada com Sucesso!");
    }//GEN-LAST:event_bntCargaInicialActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (txtCategoria.getText() == null || txtCategoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome da Categoria deve ser Informado!");
        } else {
            if (txtPotencia.getText() == null || txtPotencia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Potencia deve ser Informada!");
            } else {

                try {
                    Categoria novaCategoria = new Categoria(txtCategoria.getText(),
                            Integer.parseInt(txtPotencia.getText()));

                    listaCategoria.put(txtCategoria.getText(), novaCategoria);

                    JOptionPane.showMessageDialog(this, "Categoria Cadastrada!");
                    txtCategoria.setText(" ");
                    txtPotencia.setText(" ");
                    txtCategoria.grabFocus();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Categoria!");
                }
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CadCategoria dialog = new CadCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCargaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbPotencia;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtPotencia;
    // End of variables declaration//GEN-END:variables
}
