package apresentacao;

import Negocio.Comercial;
import Negocio.Edificacao;
import Negocio.Residencial;
import java.util.HashMap;
import java.util.Map;

public class CadEdificacao extends javax.swing.JDialog {

    protected enum Abas {

        residencial(0), comercial(1);

        private int valor;

        private Abas(int valor) {
            this.valor = valor;
        }
    }

    /**
     * Creates new form CadResidencial
     */
    private Map<String, Edificacao> edificacoes;

    public CadEdificacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        edificacoes = new HashMap<String, Edificacao>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbCadastrar = new javax.swing.JButton();
        TabbedPannel = new javax.swing.JTabbedPane();
        tRes = new javax.swing.JPanel();
        lbQtdMoradores = new javax.swing.JLabel();
        lbResponsavel = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        ResRes = new javax.swing.JTextField();
        TipoRes = new javax.swing.JTextField();
        lbExemplo = new javax.swing.JLabel();
        EndRes = new javax.swing.JTextField();
        NumRes = new javax.swing.JTextField();
        QtdRes = new javax.swing.JTextField();
        tCom = new javax.swing.JPanel();
        TipoCom = new javax.swing.JTextField();
        EndCom = new javax.swing.JTextField();
        NumCom = new javax.swing.JTextField();
        lbEmpresa = new javax.swing.JLabel();
        lbRamo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EmpCom = new javax.swing.JTextField();
        lbResponsavel1 = new javax.swing.JLabel();
        ResCom = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        lbQtdMoradores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbQtdMoradores.setText("Qtd. Moradores:");

        lbResponsavel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbResponsavel.setText("Responsável:");

        lbTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTipo.setText("Tipo:");

        lbEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEndereco.setText("Endereço:");

        lbNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNumero.setText("Número:");

        lbExemplo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbExemplo.setText("(Casa, Apartamento, ...)");

        javax.swing.GroupLayout tResLayout = new javax.swing.GroupLayout(tRes);
        tRes.setLayout(tResLayout);
        tResLayout.setHorizontalGroup(
            tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(lbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbQtdMoradores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EndRes)
                    .addGroup(tResLayout.createSequentialGroup()
                        .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tResLayout.createSequentialGroup()
                                .addComponent(TipoRes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbExemplo))
                            .addComponent(QtdRes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumRes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 199, Short.MAX_VALUE))
                    .addComponent(ResRes))
                .addContainerGap())
        );
        tResLayout.setVerticalGroup(
            tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsavel)
                    .addComponent(ResRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(TipoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExemplo))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(EndRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumero)
                    .addComponent(NumRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtdRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQtdMoradores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPannel.addTab("Residencial", tRes);

        lbEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpresa.setText("Empresa:");

        lbRamo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRamo.setText("Ramo de Atividade:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Endereço:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Número:");

        lbResponsavel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbResponsavel1.setText("Responsável:");

        javax.swing.GroupLayout tComLayout = new javax.swing.GroupLayout(tCom);
        tCom.setLayout(tComLayout);
        tComLayout.setHorizontalGroup(
            tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tComLayout.createSequentialGroup()
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbResponsavel1)
                            .addComponent(lbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpCom)
                            .addComponent(EndCom)
                            .addComponent(ResCom)))
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tComLayout.createSequentialGroup()
                                .addComponent(lbRamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tComLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumCom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 320, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tComLayout.setVerticalGroup(
            tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tComLayout.createSequentialGroup()
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbResponsavel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ResCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(EmpCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbRamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(TipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(EndCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tComLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(NumCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        TabbedPannel.addTab("Comercial", tCom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCadastrar)
                .addContainerGap())
            .addComponent(TabbedPannel)
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jbCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        Edificacao e = null;
        if (TabbedPannel.getSelectedIndex() == Abas.residencial.valor) {
            e = new Residencial(ResRes.getText(),
                    EndRes.getText(),
                    Integer.parseInt(NumRes.getText()),
                    Integer.parseInt(QtdRes.getText()),
                    TipoRes.getText());
            edificacoes.put(EndRes.getText(), e);
        } else {
            e = new Comercial(ResCom.getText(),
                    EndCom.getText(),
                    Integer.parseInt(NumCom.getText()),
                    TipoCom.getText());
            edificacoes.put(EndCom.getText(), e);
        }
        LimparCampos();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    public Map<String, Edificacao> getEdificacoes() {
        return this.edificacoes;
    }

    private void LimparCampos() {
        ResCom.setText("");
        EndCom.setText("");
        NumCom.setText("");
        TipoCom.setText("");
        EmpCom.setText("");
        ResRes.setText("");
        EndRes.setText("");
        NumRes.setText("");
        QtdRes.setText("");
        TipoRes.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEdificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEdificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEdificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEdificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadEdificacao dialog = new CadEdificacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmpCom;
    private javax.swing.JTextField EndCom;
    private javax.swing.JTextField EndRes;
    private javax.swing.JTextField NumCom;
    private javax.swing.JTextField NumRes;
    private javax.swing.JTextField QtdRes;
    private javax.swing.JTextField ResCom;
    private javax.swing.JTextField ResRes;
    private javax.swing.JTabbedPane TabbedPannel;
    private javax.swing.JTextField TipoCom;
    private javax.swing.JTextField TipoRes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbExemplo;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbQtdMoradores;
    private javax.swing.JLabel lbRamo;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbResponsavel1;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JPanel tCom;
    private javax.swing.JPanel tRes;
    // End of variables declaration//GEN-END:variables
}
