package exemplo.rpc.hello;
//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!

public interface hello {

    public static final int _def_pno = 1;
    public static final int _def_vno = 1;
    public static final int _sendHello_proc = 1;

    public String sendHello(String in_arg) throws netbula.ORPC.rpc_err;
}
