package br.com.analizador;

public interface Constants extends ScannerConstants, ParserConstants {

    int EPSILON = 0;
    int DOLLAR = 1;
    int t_UNION = 2;
    int t_ALL = 3;
    int t_UPDATE = 4;
    int t_SET = 5;
    int t_INSERT = 6;
    int t_INTO = 7;
    int t_VALUES = 8;
    int t_DELETE = 9;
    int t_FROM = 10;
    int t_SELECT = 11;
    int t_DISTINCT = 12;
    int t_AS = 13;
    int t_JOIN = 14;
    int t_CROSS = 15;
    int t_NATURAL = 16;
    int t_INNER = 17;
    int t_FULL = 18;
    int t_LEFT = 19;
    int t_RIGHT = 20;
    int t_OUTER = 21;
    int t_ON = 22;
    int t_USING = 23;
    int t_WHERE = 24;
    int t_HAVING = 25;
    int t_ORDER = 26;
    int t_GROUP = 27;
    int t_BY = 28;
    int t_TIMESTAMP = 29;
    int t_UPPER = 30;
    int t_MONTH = 31;
    int t_YEAR = 32;
    int t_COUNT = 33;
    int t_SUM = 34;
    int t_MAX = 35;
    int t_MIN = 36;
    int t_AVG = 37;
    int t_NULL = 38;
    int t_DESC = 39;
    int t_ASC = 40;
    int t_NOT = 41;
    int t_AND = 42;
    int t_OR = 43;
    int t_LIKE = 44;
    int t_ESCAPE = 45;
    int t_IS = 46;
    int t_BETWEEN = 47;
    int t_IN = 48;
    int t_CHAR = 49;
    int t_CHARACTER = 50;
    int t_INTEGER = 51;
    int t_VARCHAR2 = 52;
    int t_VARCHAR = 53;
    int t_INT = 54;
    int t_NUMBER = 55;
    int t_NUMERIC = 56;
    int t_SMALLINT = 57;
    int t_DATE = 58;
    int t_TIME = 59;
    int t_DEFAULT = 60;
    int t_PRIMARY = 61;
    int t_KEY = 62;
    int t_FOREIGN = 63;
    int t_REFERENCES = 64;
    int t_MATCH = 65;
    int t_PARTIAL = 66;
    int t_CASCADE = 67;
    int t_NO = 68;
    int t_ACTION = 69;
    int t_UNIQUE = 70;
    int t_CHECK = 71;
    int t_CREATE = 72;
    int t_TABLE = 73;
    int t_RESTRICT = 74;
    int t_DROP = 75;
    int t_ADD = 76;
    int t_CONSTRAINT = 77;
    int t_MODIFY = 78;
    int t_INDEX = 79;
    int t_DESCRIBE = 80;
    int t_WORK = 81;
    int t_COMMIT = 82;
    int t_ROLLBACK = 83;
    int t_ALTER = 84;
    int t_COLUMN = 85;
    int t_TOKEN_86 = 86; //"("
    int t_TOKEN_87 = 87; //")"
    int t_TOKEN_88 = 88; //"*"
    int t_TOKEN_89 = 89; //"+"
    int t_TOKEN_90 = 90; //","
    int t_TOKEN_91 = 91; //"-"
    int t_TOKEN_92 = 92; //"."
    int t_TOKEN_93 = 93; //"/"
    int t_TOKEN_94 = 94; //":"
    int t_TOKEN_95 = 95; //";"
    int t_TOKEN_96 = 96; //"<"
    int t_TOKEN_97 = 97; //"="
    int t_TOKEN_98 = 98; //">"
    int t_TOKEN_99 = 99; //"<>"
    int t_TOKEN_100 = 100; //"<="
    int t_TOKEN_101 = 101; //">="
    int t_TOKEN_102 = 102; //"'"
    int t_ident = 103;
    int t_integer_ = 104;
    int t_float_ = 105;
    int t_Data = 106;
    int t_SQLString = 107;
}