package br.com.analizador;

public interface ParserConstants {

    int START_SYMBOL = 108;
    int FIRST_NON_TERMINAL = 108;
    int FIRST_SEMANTIC_ACTION = 307;
    int[][] PARSER_TABLE = new LeituraMatrizArquivo().getLeituraMatriz(199, 107, "ParserConstants");
    int[][] PRODUCTIONS = {
        {109, 110},
        {112},
        {117},
        {121},
        {122},
        {227},
        {280},
        {284},
        {294},
        {111},
        {95},
        {0},
        {134, 113},
        {2, 114, 134, 113},
        {0},
        {3},
        {0},
        {112},
        {124},
        {129},
        {133},
        {80, 103, 322},
        {39, 103, 322},
        {4, 192, 332, 5, 342, 127, 125, 346},
        {162},
        {0},
        {180, 335, 97, 200, 343},
        {126, 128},
        {304, 126, 128},
        {0},
        {6, 7, 334, 192, 332, 132, 130, 335},
        {131},
        {112},
        {8, 305, 188, 306},
        {305, 178, 306},
        {0},
        {9, 10, 344, 192, 332, 125, 345},
        {138, 140, 125, 137, 136, 135},
        {164},
        {0},
        {163},
        {0},
        {165},
        {0},
        {11, 139, 166},
        {12},
        {3},
        {0},
        {10, 141},
        {146, 142},
        {143, 142},
        {0},
        {144},
        {150},
        {304, 146},
        {103, 149, 147},
        {148, 193},
        {0},
        {13},
        {0},
        {92, 103},
        {0},
        {154},
        {151},
        {153, 14, 146, 152},
        {161},
        {0},
        {155},
        {0},
        {15, 14, 146},
        {160, 156},
        {17},
        {157},
        {159, 158},
        {21},
        {0},
        {18},
        {19},
        {20},
        {16},
        {0},
        {22, 200},
        {23, 305, 178, 306},
        {24, 199},
        {25, 199},
        {26, 28, 194},
        {27, 28, 188},
        {168, 167},
        {304, 168, 167},
        {0},
        {200, 169},
        {88},
        {13, 193},
        {0},
        {172, 305, 200, 171, 306},
        {304, 200, 171},
        {0},
        {29},
        {30},
        {31},
        {32},
        {177, 305, 174, 306},
        {88},
        {175},
        {176, 200},
        {12},
        {0},
        {33},
        {34},
        {35},
        {36},
        {37},
        {180, 335, 179},
        {304, 180, 335, 179},
        {0},
        {103, 181},
        {92, 182},
        {0},
        {103},
        {88},
        {184, 103, 333},
        {85},
        {0},
        {183, 186},
        {304, 183, 186},
        {0},
        {305, 185, 306},
        {0},
        {190, 336, 189},
        {304, 190, 336, 189},
        {0},
        {180},
        {191, 331},
        {105, 329},
        {104, 328},
        {107, 330},
        {106},
        {212},
        {38},
        {103},
        {103},
        {196, 195},
        {304, 196, 195},
        {0},
        {197, 198},
        {180},
        {104},
        {39},
        {40},
        {0},
        {200},
        {202, 201},
        {221, 202, 201},
        {0},
        {204, 205, 203},
        {214, 204, 205, 203},
        {0},
        {213},
        {0},
        {211, 206},
        {209},
        {173},
        {170},
        {207},
        {305, 208, 306},
        {200},
        {115},
        {190, 210},
        {222},
        {0},
        {91},
        {0},
        {94, 103},
        {41},
        {215},
        {216},
        {88},
        {93},
        {89},
        {91},
        {42},
        {43},
        {44, 219, 218},
        {45, 107},
        {0},
        {107},
        {212},
        {46, 204, 191},
        {97},
        {99},
        {96},
        {100},
        {98},
        {101},
        {220},
        {204, 223},
        {225},
        {224},
        {217},
        {47, 190, 42, 190},
        {48, 305, 226, 306},
        {188},
        {115},
        {229, 228},
        {81},
        {0},
        {82},
        {83},
        {104},
        {305, 230, 328, 306, 317},
        {305, 230, 328, 306, 318},
        {305, 230, 328, 306, 320},
        {104, 328, 233},
        {304, 104, 328},
        {0},
        {243},
        {241},
        {239, 316},
        {57},
        {237},
        {58, 319},
        {236},
        {235},
        {29, 231},
        {59, 231},
        {267, 305, 232, 306, 314},
        {268, 305, 232, 306, 315},
        {55},
        {56},
        {51},
        {54},
        {242, 248},
        {53},
        {52},
        {244, 247},
        {49},
        {50},
        {60, 246},
        {107},
        {104},
        {105},
        {106},
        {251, 250},
        {304, 251, 250},
        {0},
        {183, 310, 234, 311, 253},
        {258},
        {265},
        {277},
        {278},
        {257},
        {240},
        {64, 326, 103, 332, 145},
        {305, 263, 306},
        {0},
        {77, 254, 313},
        {260, 313},
        {0},
        {261, 312, 252},
        {252},
        {256, 255},
        {0},
        {245},
        {257},
        {213, 191, 324},
        {191, 323},
        {61, 62, 325, 187},
        {103},
        {103},
        {63, 62, 327, 187, 64, 326, 192, 332, 116, 275, 266},
        {305, 263, 306},
        {0},
        {305, 103, 333, 306},
        {0},
        {103, 333, 264},
        {304, 263},
        {0},
        {299, 266},
        {0},
        {269},
        {273},
        {22, 274, 270},
        {67},
        {271},
        {5, 272},
        {191},
        {60},
        {68, 69},
        {9},
        {4},
        {65, 276},
        {0},
        {18},
        {66},
        {70, 187},
        {71, 305, 200, 306},
        {251},
        {253},
        {72, 281},
        {282},
        {301},
        {73, 120},
        {192, 308, 305, 279, 283, 306, 309},
        {13, 305, 134, 306},
        {118},
        {119},
        {304, 279, 283},
        {0},
        {75, 285},
        {286},
        {303, 337},
        {73, 146, 321},
        {76, 288},
        {249},
        {253},
        {291},
        {290},
        {5, 245},
        {75, 60},
        {75, 293},
        {183, 341},
        {61, 62, 338},
        {63, 62, 259, 339},
        {77, 261, 340},
        {84, 73, 146, 295},
        {287},
        {292},
        {123},
        {78, 103, 333, 234},
        {183, 198},
        {296, 298},
        {304, 296, 298},
        {0},
        {103},
        {302, 303, 336, 22, 192, 332, 305, 297, 306},
        {70},
        {0},
        {79, 300},
        {90},
        {86},
        {87}
    };
    String[] PARSER_ERROR = {
        "",
        "esperando fim de comando",
        "esperando UNION",
        "esperando ALL",
        "esperando UPDATE",
        "esperando SET",
        "esperando INSERT",
        "esperando INTO",
        "esperando VALUES",
        "esperando DELETE",
        "esperando FROM",
        "esperando SELECT",
        "esperando DISTINCT",
        "esperando AS",
        "esperando JOIN",
        "esperando CROSS",
        "esperando NATURAL",
        "esperando INNER",
        "esperando FULL",
        "esperando LEFT",
        "esperando RIGHT",
        "esperando OUTER",
        "esperando ON",
        "esperando USING",
        "esperando WHERE",
        "esperando HAVING",
        "esperando ORDER",
        "esperando GROUP",
        "esperando BY",
        "esperando TIMESTAMP",
        "esperando UPPER",
        "esperando MONTH",
        "esperando YEAR",
        "esperando COUNT",
        "esperando SUM",
        "esperando MAX",
        "esperando MIN",
        "esperando AVG",
        "esperando NULL",
        "esperando DESC",
        "esperando ASC",
        "esperando NOT",
        "esperando AND",
        "esperando OR",
        "esperando LIKE",
        "esperando ESCAPE",
        "esperando IS",
        "esperando BETWEEN",
        "esperando IN",
        "esperando CHAR",
        "esperando CHARACTER",
        "esperando INTEGER",
        "esperando VARCHAR2",
        "esperando VARCHAR",
        "esperando INT",
        "esperando NUMBER",
        "esperando NUMERIC",
        "esperando SMALLINT",
        "esperando DATE",
        "esperando TIME",
        "esperando DEFAULT",
        "esperando PRIMARY",
        "esperando KEY",
        "esperando FOREIGN",
        "esperando REFERENCES",
        "esperando MATCH",
        "esperando PARTIAL",
        "esperando CASCADE",
        "esperando NO",
        "esperando ACTION",
        "esperando UNIQUE",
        "esperando CHECK",
        "esperando CREATE",
        "esperando TABLE",
        "esperando RESTRICT",
        "esperando DROP",
        "esperando ADD",
        "esperando CONSTRAINT",
        "esperando MODIFY",
        "esperando INDEX",
        "esperando DESCRIBE",
        "esperando WORK",
        "esperando COMMIT",
        "esperando ROLLBACK",
        "esperando ALTER",
        "esperando COLUMN",
        "esperando \"(\"",
        "esperando \")\"",
        "esperando \"*\"",
        "esperando \"+\"",
        "esperando \",\"",
        "esperando \"-\"",
        "esperando \".\"",
        "esperando \"/\"",
        "esperando \":\"",
        "esperando \";\"",
        "esperando \"<\"",
        "esperando \"=\"",
        "esperando \">\"",
        "esperando \"<>\"",
        "esperando \"<=\"",
        "esperando \">=\"",
        "esperando \"'\"",
        "esperando identificador ou alias",
        "esperando literal intero",
        "esperando literal de ponto flutuante",
        "esperando Data",
        "esperando SQLString",
        "esperando UPDATE ou INSERT ou DELETE ou SELECT ou DESC ou CREATE ou DROP ou DESCRIBE ou COMMIT ou ROLLBACK ou ALTER",
        "esperando UPDATE ou INSERT ou DELETE ou SELECT ou DESC ou CREATE ou DROP ou DESCRIBE ou COMMIT ou ROLLBACK ou ALTER",
        "esperando ';'",
        "esperando DESC ou DESCRIBE",
        "esperando SELECT",
        "esperando UNION ou UNION ou ')' ou ';'",
        "esperando ALL ou SELECT",
        "esperando SELECT",
        "esperando ON ou MATCH ou NO ou '(' ou ')' ou ',' ou ';'",
        "esperando UPDATE",
        "esperando identificador ou alias",
        "esperando AS",
        "esperando AS ou identificador ou alias",
        "esperando INSERT",
        "esperando DELETE",
        "esperando MODIFY",
        "esperando UPDATE",
        "esperando UNION ou UNION ou WHERE ou HAVING ou ORDER ou GROUP ou ')' ou ';'",
        "esperando identificador ou alias",
        "esperando identificador ou alias",
        "esperando WHERE ou ,' ou ';'",
        "esperando INSERT",
        "esperando VALUES ou SELECT",
        "esperando VALUES",
        "esperando VALUES ou SELECT ou '('",
        "esperando DELETE",
        "esperando SELECT",
        "esperando UNION ou UNION ou ORDER ou ')' ou ';'",
        "esperando UNION ou UNION ou HAVING ou ORDER ou ')' ou ';'",
        "esperando UNION ou UNION ou HAVING ou ORDER ou GROUP ou ')' ou ';'",
        "esperando SELECT",
        "esperando ALL ou DISTINCT ou TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '*' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando FROM",
        "esperando identificador ou alias",
        "esperando UNION ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou WHERE ou HAVING ou ORDER ou GROUP ou )' ou ',' ou ';'",
        "esperando JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou ','",
        "esperando ','",
        "esperando '(' ou ')' ou ',' ou ';'",
        "esperando identificador ou alias",
        "esperando UNION ou AS ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou ON ou USING ou WHERE ou HAVING ou ORDER ou GROUP ou DROP ou ADD ou MODIFY ou ')' ou ',' ou ';' ou identificador ou alias'",
        "esperando AS ou identificador ou alias",
        "esperando UNION ou AS ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou ON ou USING ou WHERE ou HAVING ou ORDER ou GROUP ou DROP ou ADD ou MODIFY ou ')' ou ',' ou '.' ou ';' ou identificador ou alias'",
        "esperando JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT",
        "esperando JOIN ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT",
        "esperando UNION ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou ON ou USING ou WHERE ou HAVING ou ORDER ou GROUP ou ')' ou ',' ou ';'",
        "esperando JOIN ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT",
        "esperando CROSS",
        "esperando NATURAL ou INNER ou FULL ou LEFT ou RIGHT",
        "esperando INNER ou FULL ou LEFT ou RIGHT",
        "esperando FULL ou LEFT ou RIGHT",
        "esperando JOIN ou OUTER",
        "esperando FULL ou LEFT ou RIGHT",
        "esperando NATURAL ou INNER ou FULL ou LEFT ou RIGHT",
        "esperando ON ou USING",
        "esperando WHERE",
        "esperando HAVING",
        "esperando ORDER",
        "esperando GROUP",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '*' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando FROM ou ','",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '*' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando FROM ou AS ou ','",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR",
        "esperando ')' ou ','",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR",
        "esperando COUNT ou SUM ou MAX ou MIN ou AVG",
        "esperando DISTINCT ou TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '*' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando DISTINCT ou TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando DISTINCT ou TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando COUNT ou SUM ou MAX ou MIN ou AVG",
        "esperando identificador ou alias",
        "esperando ')' ou ','",
        "esperando identificador ou alias",
        "esperando UNION ou FROM ou AS ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou WHERE ou HAVING ou ORDER ou GROUP ou DESC ou ASC ou NOT ou AND ou OR ou LIKE ou IS ou BETWEEN ou IN ou ')' ou '*' ou '+' ou ',' ou '-' ou '.' ou '/' ou ';' ou '<' ou '=' ou '>' ou '<>' ou '<=' ou '>='",
        "esperando '*' ou identificador ou alias'",
        "esperando COLUMN ou identificador ou alias",
        "esperando COLUMN ou identificador ou alias",
        "esperando COLUMN ou identificador ou alias",
        "esperando ')' ou ','",
        "esperando REFERENCES ou '(' ou ')' ou ',' ou ';'",
        "esperando NULL ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando UNION ou UNION ou HAVING ou ORDER ou ')' ou ',' ou ';'",
        "esperando NULL ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando NULL",
        "esperando identificador ou alias",
        "esperando identificador ou alias",
        "esperando identificador ou alias ou literal inteiro",
        "esperando UNION ou UNION ou ')' ou ',' ou ';'",
        "esperando identificador ou alias ou literal inteiro",
        "esperando identificador ou alias ou literal inteiro",
        "esperando UNION ou UNION ou DESC ou ASC ou ')' ou ',' ou ';'",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando UNION ou FROM ou AS ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou WHERE ou HAVING ou ORDER ou GROUP ou ')' ou ',' ou ';' ou '<' ou '=' ou '>' ou '<>' ou '<=' ou '>='",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando UNION ou FROM ou AS ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou WHERE ou HAVING ou ORDER ou GROUP ou AND ou OR ou ')' ou '*' ou '+' ou ',' ou '-' ou '/' ou ';' ou '<' ou '=' ou '>' ou '<>' ou '<=' ou '>='",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou LIKE ou BETWEEN ou IN ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou '(' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando '('",
        "esperando SELECT ou TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou NOT ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando NULL ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando UNION ou FROM ou AS ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou WHERE ou HAVING ou ORDER ou GROUP ou NOT ou AND ou OR ou LIKE ou IS ou BETWEEN ou IN ou )' ou '*' ou '+' ou ',' ou '-' ou '/' ou ';' ou '<' ou '=' ou '>' ou '<>' ou '<=' ou '>='",
        "esperando TIMESTAMP ou UPPER ou MONTH ou YEAR ou COUNT ou SUM ou MAX ou MIN ou AVG ou NULL ou '(' ou '-' ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando ':'",
        "esperando NOT",
        "esperando AND ou OR ou '*' ou '+' ou '-' ou '/'",
        "esperando '*' ou '+' ou '-' ou '/'",
        "esperando AND ou OR",
        "esperando LIKE",
        "esperando UNION ou FROM ou AS ou UNION ou JOIN ou CROSS ou NATURAL ou INNER ou FULL ou LEFT ou RIGHT ou WHERE ou HAVING ou ORDER ou GROUP ou AND ou OR ou ESCAPE ou ')' ou '*' ou '+' ou ',' ou '-' ou '/' ou ';' ou '<' ou '=' ou '>' ou '<>' ou '<=' ou '>='",
        "esperando ':' ou SQLString'",
        "esperando IS",
        "esperando '<' ou '=' ou '>' ou '<>' ou '<=' ou '>='",
        "esperando NOT ou LIKE ou IS ou BETWEEN ou IN",
        "esperando LIKE ou BETWEEN ou IN",
        "esperando BETWEEN",
        "esperando IN",
        "esperando SELECT ou NULL ou ':' ou identificador ou alias ou literal inteiro ou literal de ponto futuante ou Data ou SQLString'",
        "esperando COMMIT ou ROLLBACK",
        "esperando WORK ou ';'",
        "esperando COMMIT ou ROLLBACK",
        "esperando literal inteiro",
        "esperando '('",
        "esperando literal inteiro",
        "esperando ')' ou ','",
        "esperando TIMESTAMP ou CHAR ou CHARACTER ou INTEGER ou VARCHAR2 ou VARCHAR ou INT ou NUMBER ou NUMERIC ou SMALLINT ou DATE ou TIME",
        "esperando TIMESTAMP",
        "esperando TIME",
        "esperando NUMBER ou NUMERIC",
        "esperando '",
        "esperando INTEGER ou INT",
        "esperando REFERENCES",
        "esperando VARCHAR2 ou VARCHAR",
        "esperando VARCHAR2 ou VARCHAR",
        "esperando CHAR ou CHARACTER",
        "esperando CHAR ou CHARACTER",
        "esperando DEFAULT",
        "esperando literal inteiro ou literal de ponto futuante ou Data ou SQLString",
        "esperando '('",
        "esperando '('",
        "esperando COLUMN ou identificador ou alias",
        "esperando ',' ou ';'",
        "esperando COLUMN ou identificador ou alias",
        "esperando NULL ou NOT ou PRIMARY ou FOREIGN ou REFERENCES ou UNIQUE ou CHECK",
        "esperando NULL ou NOT ou PRIMARY ou FOREIGN ou REFERENCES ou UNIQUE ou CHECK ou CONSTRAINT ou ')' ou ',' ou ';'",
        "esperando identificador ou alias",
        "esperando NULL ou NOT ou DEFAULT",
        "esperando NULL ou NOT ou DEFAULT",
        "esperando NULL ou NOT",
        "esperando PRIMARY",
        "esperando identificador ou alias",
        "esperando NULL ou NOT ou PRIMARY ou FOREIGN ou REFERENCES ou UNIQUE ou CHECK",
        "esperando identificador ou alias",
        "esperando '('",
        "esperando identificador ou alias",
        "esperando ')' ou ','",
        "esperando FOREIGN",
        "esperando ON ou NO ou ')' ou ',' ou ';'",
        "esperando NUMERIC",
        "esperando NUMBER",
        "esperando ON",
        "esperando SET ou CASCADE",
        "esperando SET",
        "esperando NULL ou DEFAULT",
        "esperando NO",
        "esperando UPDATE ou DELETE",
        "esperando ON ou MATCH ou NO ou ')' ou ',' ou ';'",
        "esperando FULL ou PARTIAL",
        "esperando UNIQUE",
        "esperando CHECK",
        "esperando NULL ou NOT ou PRIMARY ou FOREIGN ou REFERENCES ou UNIQUE ou CHECK ou CONSTRAINT ou COLUMN ou ')' ou ',' ou identificador ou alias'",
        "esperando CREATE",
        "esperando UNIQUE ou TABLE ou INDEX",
        "esperando TABLE",
        "esperando ')' ou ','",
        "esperando DROP",
        "esperando TABLE ou INDEX",
        "esperando TABLE",
        "esperando ADD",
        "esperando NULL ou NOT ou PRIMARY ou FOREIGN ou REFERENCES ou UNIQUE ou CHECK ou CONSTRAINT ou COLUMN ou ';' ou identificador ou alias'",
        "esperando SET ou DROP",
        "esperando SET",
        "esperando DROP",
        "esperando DROP",
        "esperando PRIMARY ou FOREIGN ou CONSTRAINT ou COLUMN ou identificador ou alias",
        "esperando ALTER",
        "esperando DROP ou ADD ou MODIFY",
        "esperando COLUMN ou identificador ou alias",
        "esperando COLUMN ou identificador ou alias",
        "esperando ')' ou ','",
        "esperando ON ou NO",
        "esperando identificador ou alias",
        "esperando UNIQUE ou INDEX",
        "esperando UNIQUE ou INDEX",
        "esperando INDEX",
        "esperando ','",
        "esperando '('",
        "esperando ')'"
    };
}