package projeto.corba.sistemaBancarioCorba;

/**
 * sistemaBancarioCorba/_InterfaceCorbaStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from SistemaBancarioCorba.idl
 * Terça-feira, 6 de Dezembro de 2011 20h49min29s BRST
 */
public class _InterfaceCorbaStub extends org.omg.CORBA.portable.ObjectImpl implements InterfaceCorba {

    public boolean emprestimo(int nrConta, String senha, double valor, org.omg.CORBA.StringHolder retorno) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("emprestimo", true);
            $out.write_long(nrConta);
            $out.write_string(senha);
            $out.write_double(valor);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            retorno.value = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return emprestimo(nrConta, senha, valor, retorno);
        } finally {
            _releaseReply($in);
        }
    } // emprestimo

    public boolean pagamento(int nrConta, String senha, int nrTitulo, double valor, org.omg.CORBA.StringHolder retorno) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("pagamento", true);
            $out.write_long(nrConta);
            $out.write_string(senha);
            $out.write_long(nrTitulo);
            $out.write_double(valor);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            retorno.value = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return pagamento(nrConta, senha, nrTitulo, valor, retorno);
        } finally {
            _releaseReply($in);
        }
    } // pagamento

    public boolean visualizarLimite(int nrConta, String senha, org.omg.CORBA.StringHolder retorno) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("visualizarLimite", true);
            $out.write_long(nrConta);
            $out.write_string(senha);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            retorno.value = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return visualizarLimite(nrConta, senha, retorno);
        } finally {
            _releaseReply($in);
        }
    } // visualizarLimite
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:sistemaBancarioCorba/InterfaceCorba:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(java.io.ObjectInputStream s) throws java.io.IOException {
        String str = s.readUTF();
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
        try {
            org.omg.CORBA.Object obj = orb.string_to_object(str);
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            _set_delegate(delegate);
        } finally {
            orb.destroy();
        }
    }

    private void writeObject(java.io.ObjectOutputStream s) throws java.io.IOException {
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
        try {
            String str = orb.object_to_string(this);
            s.writeUTF(str);
        } finally {
            orb.destroy();
        }
    }
} // class _InterfaceCorbaStub
