package projeto.corba.sistemaBancarioCorba;

/**
 * sistemaBancarioCorba/InterfaceCorba.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from SistemaBancarioCorba.idl
 * Terça-feira, 6 de Dezembro de 2011 20h49min29s BRST
 */
public interface InterfaceCorba extends InterfaceCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface InterfaceCorba
