package projeto.corba.sistemaBancarioCorba;

/**
 * sistemaBancarioCorba/InterfaceCorbaPOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from SistemaBancarioCorba.idl
 * Terça-feira, 6 de Dezembro de 2011 20h49min29s BRST
 */
public abstract class InterfaceCorbaPOA extends org.omg.PortableServer.Servant
        implements InterfaceCorbaOperations, org.omg.CORBA.portable.InvokeHandler {

    // Constructors
    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("emprestimo", new java.lang.Integer(0));
        _methods.put("pagamento", new java.lang.Integer(1));
        _methods.put("visualizarLimite", new java.lang.Integer(2));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
        if (__method == null) {
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        switch (__method.intValue()) {
            case 0: // sistemaBancarioCorba/InterfaceCorba/emprestimo
            {
                int nrConta = in.read_long();
                String senha = in.read_string();
                double valor = in.read_double();
                org.omg.CORBA.StringHolder retorno = new org.omg.CORBA.StringHolder();
                boolean $result = false;
                $result = this.emprestimo(nrConta, senha, valor, retorno);
                out = $rh.createReply();
                out.write_boolean($result);
                out.write_string(retorno.value);
                break;
            }

            case 1: // sistemaBancarioCorba/InterfaceCorba/pagamento
            {
                int nrConta = in.read_long();
                String senha = in.read_string();
                int nrTitulo = in.read_long();
                double valor = in.read_double();
                org.omg.CORBA.StringHolder retorno = new org.omg.CORBA.StringHolder();
                boolean $result = false;
                $result = this.pagamento(nrConta, senha, nrTitulo, valor, retorno);
                out = $rh.createReply();
                out.write_boolean($result);
                out.write_string(retorno.value);
                break;
            }

            case 2: // sistemaBancarioCorba/InterfaceCorba/visualizarLimite
            {
                int nrConta = in.read_long();
                String senha = in.read_string();
                org.omg.CORBA.StringHolder retorno = new org.omg.CORBA.StringHolder();
                boolean $result = false;
                $result = this.visualizarLimite(nrConta, senha, retorno);
                out = $rh.createReply();
                out.write_boolean($result);
                out.write_string(retorno.value);
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:sistemaBancarioCorba/InterfaceCorba:1.0"};

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
        return (String[]) __ids.clone();
    }

    public InterfaceCorba _this() {
        return InterfaceCorbaHelper.narrow(
                super._this_object());
    }

    public InterfaceCorba _this(org.omg.CORBA.ORB orb) {
        return InterfaceCorbaHelper.narrow(
                super._this_object(orb));
    }
} // class InterfaceCorbaPOA
