package projeto.corba.sistemaBancarioCorba;

/**
 * sistemaBancarioCorba/InterfaceCorbaOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from SistemaBancarioCorba.idl
 * Terça-feira, 6 de Dezembro de 2011 20h49min29s BRST
 */
public interface InterfaceCorbaOperations {

    boolean emprestimo(int nrConta, String senha, double valor, org.omg.CORBA.StringHolder retorno);

    boolean pagamento(int nrConta, String senha, int nrTitulo, double valor, org.omg.CORBA.StringHolder retorno);

    boolean visualizarLimite(int nrConta, String senha, org.omg.CORBA.StringHolder retorno);
} // interface InterfaceCorbaOperations
