package projeto.corba.sistemaBancarioCorba;

/**
 * sistemaBancarioCorba/InterfaceCorbaHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from SistemaBancarioCorba.idl
 * Terça-feira, 6 de Dezembro de 2011 20h49min29s BRST
 */
public final class InterfaceCorbaHolder implements org.omg.CORBA.portable.Streamable {

    public InterfaceCorba value = null;

    public InterfaceCorbaHolder() {
    }

    public InterfaceCorbaHolder(InterfaceCorba initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = InterfaceCorbaHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        InterfaceCorbaHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return InterfaceCorbaHelper.type();
    }
}
