CREATE TABLE RASTREIO_EVTS_PESSOA_FISICA (
ID NUMERIC(10) PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
DATA_ULTIMA_CONSULTA_CREDITO TIMESTAMP NOT NULL,
LOCAL_ULTIMA_CONSULTA_CREDITO VARCHAR(250) NOT NULL,
POSSUI_DIVIDA NUMERIC(1) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);