CREATE TABLE MOVIMENTACAO_FINANCEIRA (
ID NUMERIC(10) PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
VALOR NUMERIC(10,2) NOT NULL,
DESCRICAO VARCHAR(250) NOT NULL,
DATA_MOVIMENTACAO TIMESTAMP NOT NULL,
OPERACAO VARCHAR(10) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);