CREATE TABLE GASTOS_CARTAO_CREDITO (
ID NUMERIC(10) PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
VALOR NUMERIC(10,2) NOT NULL,
DATA TIMESTAMP NOT NULL,
LOCAL VARCHAR(250) NOT NULL,
DATA_CRIACAO TIMESTAMP NOT NULL,
DATA_ATUALIZACAO TIMESTAMP NOT NULL
);