package projeto.rpc;
//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!

import netbula.ORPC.*;

public class params implements XDT {

    public String param1;
    public String param2;
    public String param3;
    public String param4;

    public XDT Clone() {
        return new params();
    }

    public XDT[] getArray(int len) {
        return new params[len];
    }

    public void xdr(XDR xdrs) throws XDRError {
        switch (xdrs.xdr_op) {
            case XDR.XDR_ENCODE:
                xdrs.enc_String(param1);
                xdrs.enc_String(param2);
                xdrs.enc_String(param3);
                xdrs.enc_String(param4);
                break;

            case XDR.XDR_DECODE:
                param1 = xdrs.dec_String();
                param2 = xdrs.dec_String();
                param3 = xdrs.dec_String();
                param4 = xdrs.dec_String();
                break;

        }
    }
};
