package projeto.rpc;
//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!

import netbula.ORPC.*;

public class SistemaBancarioRPC_cln extends ClientGeneric implements SistemaBancarioRPC {

    /**
    Construct an RPC client that is not bound to any server
     */
    public SistemaBancarioRPC_cln() throws rpc_err {
    }

	/**
	Construct an RPC client object connected to a server
	on the specified host with the specified protocol

	@param host server hostname, or URL of the RPC proxy if http is used
	@param proto protocol, can be "tcp", "udp" or "http"
	*/
	public SistemaBancarioRPC_cln(String host, String proto) throws rpc_err {
        super(host, SistemaBancarioRPC._def_pno, SistemaBancarioRPC._def_vno, proto);
    }

    /**
    Construct an RPC client object connected to a server
    on the specified host with the specified protocol and port number
    
    @param host server hostname
    @param proto protocol, can be "tcp" or "udp"
    @param port server's fixed port number
     */
    public SistemaBancarioRPC_cln(String host, String proto, int port) throws rpc_err {
        super(host, proto, port, SistemaBancarioRPC._def_pno, SistemaBancarioRPC._def_vno);
    }

    /**
    Construct an RPC client object connected to a server
    on the specified host with the specified program number,version and protocol
    
    @param host server hostname, or URL of RPC proxy
    @param proto protocol, can be "tcp", "udp" or "http"
    @param prog server's program number
    @param ver server's version number
     */
    public SistemaBancarioRPC_cln(String host, int prog, int ver, String proto) throws rpc_err {
        super(host, prog, ver, proto);
    }

    public String cadastrarCliente(String in_arg) throws rpc_err {
        XDTString _in_arg = new XDTString();
        _in_arg.value = in_arg;
        XDTString _out_arg = new XDTString();
        getClient().call(SistemaBancarioRPC._cadastrarCliente_proc, _in_arg, _out_arg);
        return _out_arg.value;
    }

    public String getCliente(String in_arg) throws rpc_err {
        XDTString _in_arg = new XDTString();
        _in_arg.value = in_arg;
        XDTString _out_arg = new XDTString();
        getClient().call(SistemaBancarioRPC._getCliente_proc, _in_arg, _out_arg);
        return _out_arg.value;
    }

    public String extrato(params in_arg) throws rpc_err {
        XDTString _out_arg = new XDTString();
        getClient().call(SistemaBancarioRPC._extrato_proc, in_arg, _out_arg);
        return _out_arg.value;
    }

    public String addHistoricoMovimentacao(String in_arg) throws rpc_err {
        XDTString _in_arg = new XDTString();
        _in_arg.value = in_arg;
        XDTString _out_arg = new XDTString();
        getClient().call(SistemaBancarioRPC._addHistoricoMovimentacao_proc, _in_arg, _out_arg);
        return _out_arg.value;
    }
}
