package projeto.rpc;
//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!

import netbula.ORPC.*;

abstract public class SistemaBancarioRPC_svcb extends Svc implements SistemaBancarioRPC {

    public SistemaBancarioRPC_svcb(int prog, int ver) {
        super(prog, ver);
    }

    public SistemaBancarioRPC_svcb() {
        super(SistemaBancarioRPC._def_pno, SistemaBancarioRPC._def_vno);
    }

    abstract public String cadastrarCliente(String in_arg);

    abstract public String getCliente(String in_arg);

    abstract public String extrato(params in_arg);

    abstract public String addHistoricoMovimentacao(String in_arg);

    public XDT proc_call(int proc, XDR inXDR) throws XDRError {
        switch (proc) {
            case 0:
                return new XDTvoid();

            case 1:
                String _out_arg1;
                try {
                    XDTString _in_arg = new XDTString();
                    _in_arg.xdr(inXDR);
                    _out_arg1 = this.cadastrarCliente(_in_arg.value);
                } catch (XDRError e) {
                    throw e;
                }
                return new XDTString(_out_arg1);

            case 2:
                String _out_arg2;
                try {
                    XDTString _in_arg = new XDTString();
                    _in_arg.xdr(inXDR);
                    _out_arg2 = this.getCliente(_in_arg.value);
                } catch (XDRError e) {
                    throw e;
                }
                return new XDTString(_out_arg2);

            case 3:
                String _out_arg3;
                try {
                    params _in_arg = new params();
                    _in_arg.xdr(inXDR);
                    _out_arg3 = this.extrato(_in_arg);
                } catch (XDRError e) {
                    throw e;
                }
                return new XDTString(_out_arg3);

            case 4:
                String _out_arg4;
                try {
                    XDTString _in_arg = new XDTString();
                    _in_arg.xdr(inXDR);
                    _out_arg4 = this.addHistoricoMovimentacao(_in_arg.value);
                } catch (XDRError e) {
                    throw e;
                }
                return new XDTString(_out_arg4);

            default:
                return null;
        }
    }
}
