package projeto.rpc;
//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!

public interface SistemaBancarioRPC {

    public static final int _def_pno = 2;
    public static final int _def_vno = 1;
    
    public static final int _cadastrarCliente_proc = 1;
    public String cadastrarCliente(String in_arg) throws netbula.ORPC.rpc_err;
    
    public static final int _getCliente_proc = 2;
    public String getCliente(String in_arg) throws netbula.ORPC.rpc_err;
    
    public static final int _extrato_proc = 3;
    public String extrato(params in_arg) throws netbula.ORPC.rpc_err;
    
    public static final int _addHistoricoMovimentacao_proc = 4;
    public String addHistoricoMovimentacao(String in_arg) throws netbula.ORPC.rpc_err;
}
