
package webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Servico", targetNamespace = "http://servidor/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Servico {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaCidades", targetNamespace = "http://servidor/", className = "webservice.GetListaCidades")
    @ResponseWrapper(localName = "getListaCidadesResponse", targetNamespace = "http://servidor/", className = "webservice.GetListaCidadesResponse")
    @Action(input = "http://servidor/Servico/getListaCidadesRequest", output = "http://servidor/Servico/getListaCidadesResponse")
    public List<String> getListaCidades();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWord", targetNamespace = "http://servidor/", className = "webservice.GetHelloWord")
    @ResponseWrapper(localName = "getHelloWordResponse", targetNamespace = "http://servidor/", className = "webservice.GetHelloWordResponse")
    @Action(input = "http://servidor/Servico/getHelloWordRequest", output = "http://servidor/Servico/getHelloWordResponse")
    public String getHelloWord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soma", targetNamespace = "http://servidor/", className = "webservice.Soma")
    @ResponseWrapper(localName = "somaResponse", targetNamespace = "http://servidor/", className = "webservice.SomaResponse")
    @Action(input = "http://servidor/Servico/somaRequest", output = "http://servidor/Servico/somaResponse")
    public double soma(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
