
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicoService", targetNamespace = "http://servidor/", wsdlLocation = "http://localhost:8084/servico?wsdl")
public class ServicoService
    extends Service
{

    private final static URL SERVICOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICOSERVICE_EXCEPTION;
    private final static QName SERVICOSERVICE_QNAME = new QName("http://servidor/", "ServicoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/servico?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOSERVICE_WSDL_LOCATION = url;
        SERVICOSERVICE_EXCEPTION = e;
    }

    public ServicoService() {
        super(__getWsdlLocation(), SERVICOSERVICE_QNAME);
    }

    public ServicoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOSERVICE_QNAME, features);
    }

    public ServicoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICOSERVICE_QNAME);
    }

    public ServicoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOSERVICE_QNAME, features);
    }

    public ServicoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Servico
     */
    @WebEndpoint(name = "ServicoPort")
    public Servico getServicoPort() {
        return super.getPort(new QName("http://servidor/", "ServicoPort"), Servico.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Servico
     */
    @WebEndpoint(name = "ServicoPort")
    public Servico getServicoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor/", "ServicoPort"), Servico.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOSERVICE_EXCEPTION!= null) {
            throw SERVICOSERVICE_EXCEPTION;
        }
        return SERVICOSERVICE_WSDL_LOCATION;
    }

}
